part of database_reverse_engineer;

//Interface only
abstract class IDMethod {
	/**
	 * Key generation via database-specific ID method
	 * (i.e. auto-increment for MySQL, sequence for Oracle, etc.).
	 */
	static const String NATIVE = "native";

	/**
	 * No RDBMS key generation (keys may be generated by the
	 * application).
	 */
	static const String NO_ID_METHOD = "none";
}